name: Run Tests

on:
  pull_request:
    paths:
      - "src/inspector/**"
      - "tests/**"
    types: [opened, synchronize, reopened, edited, ready_for_review]
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          ./venv/bin/pip install --no-cache-dir --disable-pip-version-check -r requirements-dev.txt
          ./venv/bin/pip install -e ".[test]"

      - name: Run tests
        run: |
          source venv/bin/activate
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/ --benchmark-skip -v 